language: go

sudo: required
dist: trusty

env:
- GO15VENDOREXPERIMENT=1

matrix:
  allow_failures:
    - go: tip

go:
- 1.5
- 1.6
- tip

before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

before_script:
- go vet

before_install:
- go get github.com/Masterminds/glide
- make depends

install:
- make build

script:
- go test -v .
